### PR TITLE
Port upstream unit tests

### PR DESCRIPTION
**Pull request by mineralntl**
This should help identify errors earlier during testing.

### CODE REVIEW

**Review by jwomeara — DISMISSED** [review]
LGTM, but im curious why there are always so many whitespace changes in your PRs...

**Comment by mineralntl** [comment]
Looking into the auto formatting and how I'm running mvn before pushing to eliminate that issue

**Review by apmoriarty — CHANGES_REQUESTED** [review]
The ParentQueryIteratorTest and QueryIteratorTest look good. Please revert the whitespace changes in QueryIterator and SourceManagerTest, I don't think either of those classes belong in this pr.

**Comment by mineralntl** [comment]
Removed unnecessary whitespace as requested - I'll look into the mvn formatting on my end so this isn't an issue moving forwrad.

**Review by jwomeara — APPROVED** [review]

**Review by apmoriarty — APPROVED** [review]

**Pull request merged**
