### PR TITLE
fixes #1372: handle evaluation only fields

### LINKED ISSUE #1372: evaluation only fields not used correctly in RangeStream
The evaluation only fields are fields that may not have 'e' entries in the datawave metadata table but are still valid fields to query against because they are generated automatically when ever a document is aggregated for evaluation.  This is used appropriately in the DefaultQueryPlanner when ensuring that all the fields in the query exist.
However the RangeStream will mark a node as having an UNKNOWN_FIELD by use the metadata helper getAllFields.  This results in an ABSENT stream which can screw up the executability of the query.
The best solution may be to instrument the metadata helpers to include these evaluation only fields.

### PR DESCRIPTION
**Pull request by ivakegg**
* Updated metadata utils to 1.9
    * Updated the shard query logic to set the evaluation only fields on the metadata helper
    * Updated the test case to appropriately test evaluation only fields

### CODE REVIEW

**Comment by hlgp** [comment]
LGTM.  Only question is whether the new MetadataHelper should live in datawave-metadata-utils instead.

**Comment by apmoriarty** [comment]
> LGTM. Only question is whether the new MetadataHelper should live in datawave-metadata-utils instead.

I don't think it's unreasonable to add evaluation only fields to the default implementation of the MetadataHelper.

**Review by jwomeara — DISMISSED** [review]

**Comment by ivakegg** [comment]
Working on moving the functionality into the base metadata helper class.

**Comment by ivakegg** [comment]
Moved the use of evaluation only fields into the metadata-utils.  Please re-approve.

**Review by billoley — APPROVED** [review]

**Review by hlgp — APPROVED** [review]

**Pull request merged**
