### PR TITLE
Updated jexl parsing to disable some features which we aren't using t…

### PR DESCRIPTION
**Pull request by jwomeara**
…o improve parsing performance.

### CODE REVIEW

**Review by apmoriarty — DISMISSED** [review]

**Comment by FineAndDandy** [comment]
can you retarget this to version6.5?

**Comment by apmoriarty** [comment]
Could you update the following places that still use the default JexlFeatures?

- EdgeQueryLogic line 350
- PrintingVisitor line 196, 257
- JexlAstHelper.parseQueryWithBackslashes

**Review by alerman — DISMISSED** [review]

**Comment by jwomeara** [comment]
> can you retarget this to version6.5?

done

**Comment by jwomeara** [comment]
> Could you update the following places that still use the default JexlFeatures?
> 
> * EdgeQueryLogic line 350
> * PrintingVisitor line 196, 257
> * JexlAstHelper.parseQueryWithBackslashes

done

**Review by ivakegg — APPROVED** [review]

**Review by FineAndDandy — APPROVED** [review]
thanks for taking the time to clearly mark all features we are using

**Review by apmoriarty — APPROVED** [review]

**Pull request merged**
