### PR TITLE
DATAWAVE-276: TLDFieldIndexAggregator use apply() for toKeep flag

### PR DESCRIPTION
**Pull request by FineAndDandy**
see #276

### CODE REVIEW

**Comment by drewfarris** [comment]
Nice change. `keep()` is used for determining which fields get displayed to the user while `apply()` determines which fields get loaded into the context for evaluation. Seems pretty clear we need to use the latter here.

**Comment by ivakegg** [comment]
I am sorry, but I do not get why we should use the apply if the attr filter to determine whether we are "toKeep" the attribute.  If that is required, then I surmise that the toKeep method on the attr filter is not implemented correctly.

**Comment by ivakegg** [comment]
I think I still need an answer to my query here...

**Comment by FineAndDandy** [comment]
merged into #226 since both required similar updates to the EventQueryDataFilters

**Pull request closed without merging**
