### PR TITLE
WIP: 1665: clean up failed job dirs

### PR DESCRIPTION
**Pull request by wgtong**
https://github.com/NationalSecurityAgency/datawave/issues/1665

### CODE REVIEW

**Comment by wgtong** [comment]
look into cleaning up file in the other exceptions within this class

**Comment by wgtong** [comment]
> look into cleaning up file in the other exceptions within this class
Perhaps it's better to clean up the dir at the stage in which the job flags the data to be reingested.

**Review by avgAGB — APPROVED** [review]

**Comment by wgtong** [comment]
> > look into cleaning up file in the other exceptions within this class
> > Perhaps it's better to clean up the dir at the stage in which the job flags the data to be reingested.

Any thoughts? @hlgp

**Review by mineralntl — APPROVED** [review]

**Comment by wgtong** [comment]
TODO: integration test

**Comment by wgtong** [comment]
After discussing with hannah, IngestJob has code already to clean up the directory. Somehow the partitioner is escaping it.

**Comment by wgtong** [comment]
closing for now

**Pull request closed without merging**
