### PR TITLE
remove unnecessary method from ingesthelper and clean test pt2

### PR DESCRIPTION
**Pull request by austin007008**

### CODE REVIEW

**Comment by MiguelRicardos** [comment]
Looks good to me, please squash to 1 commit.

``` 
git checkout integration
git pull
git checkout feature-clean-test-pt2
git rebase -i integration
<squash down>
git push -f
```

**Review by apmoriarty — APPROVED** [review]
LGTM

**Review by MiguelRicardos — APPROVED** [review]

**Comment by apmoriarty** [comment]
> Looks good to me, please squash to 1 commit.
> 
> ```
> git checkout integration
> git pull
> git checkout feature-clean-test-pt2
> git rebase -i integration
> <squash down>
> git push -f
> ```

The second commit is from updating the branch in the UI. In reality there is only one 'real' commit -- no cause for concern.

**Comment by jwomeara** [comment]
This method that you removed is used by one of our downstream dependents...

**Comment by austin007008** [comment]
I can't seem to find your comment on github. Also my bad, after all of the
testing I assumed it was all good.

Can you tell me what broke please?

Austin Scott

**Pull request merged**
